Publish to new apt repo

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -12,10 +12,10 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     steps:
-      - name: Set up Go 1.13
+      - name: Set up Go 1.15
         uses: actions/setup-go@v1
         with:
-          go-version: 1.13
+          go-version: 1.15
         id: go
       - name: Check out code into the Go module directory
         uses: actions/checkout@v1
@@ -47,20 +47,21 @@ jobs:
         run: |
           gem install bundler
           bundle install --jobs 4 --retry 3
-      - name: Get Build number
-        uses: einaregilsson/build-number@v1
-        with:
-          token: ${{secrets.github_token}}
       - name: Make deb package
         run: |
           touch gopath/src/github.com/kumina/unbound_exporter/dist/*
           make package
-      - name: Upload to S3 Apt repo
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          DEBSIGN: ${{ secrets.DEBSIGN }}
+          BUILD_NUMBER: ${{ github.run_number }}
+      - name: Upload to Apt repo
+        env:
+          KEY_PASSPHRASE: ${{ secrets.DEBSIGN_KEY_PASSPHRASE }}
+          APT_CREDENTIALS: ${{ secrets.APT_CREDENTIALS }}
         run: |
-          echo 'aaaaaaaa' > passphrase_file
-          echo $DEBSIGN | base64 -d | gpg --import --batch
-          bundle exec deb-s3 upload --s3-region=eu-north-1 --sign=6A2561804E290210909454E69640EFFBAA3B94A5 --gpg-options="\-\-pinentry\-mode=loopback \-\-passphrase\-file passphrase_file \-\-batch" --suite stable --origin "Andrew Rowson" --bucket apt.growse.com *.deb
+          echo $APT_CREDENTIALS > aptly-auth
+          find -type f -name "*.deb" -exec curl -f --netrc-file aptly-auth -XPOST -F file=@{} https://apttoo.growse.com/api/files/unbound-exporter \;
+          export result=$(curl -f --netrc-file aptly-auth -X POST https://apttoo.growse.com/api/repos/defaultrepo/file/unbound-exporter)
+          echo $result
+          export failed=$(echo $result | jq '.FailedFiles | length')
+          if [[ "$failed" != "0" ]]; then exit 1; fi
+          curl -f --netrc-file aptly-auth -X PUT https://apttoo.growse.com/api/publish/:./stablish
